api/urls.py
from api import views

from rest_framework import routers

router = routers.SimpleRouter()

router.register(r'chemical', views.ChemicalView, "chemical")

urlpatterns = router.urls

chemical/urls.py
from django.conf.urls import url
from django.core.urlresolvers import reverse
from django.http import HttpResponsePermanentRedirect

from chemical import ajax_views
from chemical import views
from chemical.views import *

urlpatterns = [
    url(
        r'^admin/organism-autocomplete/$',
        OrganismAutocomplete.as_view(),
        name='organism-autocomplete',
    ),
    url(
        r'^admin/preparation-autocomplete/$',
        PreparationAutocomplete.as_view(),
        name='preparation-autocomplete',
    ),
    url(
        r'^admin/category-autocomplete/$',
        CategoryAutocomplete.as_view(),
        name='category-autocomplete',
    ),
    url(
        r'^admin/gene-autocomplete/$',
        GeneAutocomplete.as_view(),
        name='gene-autocomplete',
    ),
    url(
        r'^admin/chemical-autocomplete/$',
        ChemicalAutocomplete.as_view(),
        name='chemical-autocomplete',
    ),
    url(
        r'^admin/interaction-autocomplete/$',
        InteractionAutocomplete.as_view(),
        name='interaction-autocomplete',
    ),
    url(
        r'^admin/interaction-type-autocomplete/$',
        InteractionTypeAutocomplete.as_view(),
        name='interaction-type-autocomplete',
    ),
    url(
        r'^admin/health-effect-autocomplete/$',
        HealthEffectAutocomplete.as_view(),
        name='health-effect-autocomplete',
    ),
    url(r'^chemical-disease-ajax/(?P<chemical>([A-Za-z0-9_-]+))/',
        ajax_views.chemical_disease_ajax,
        name="chemical-disease-ajax"),
    # url(r'^chemical-gene-ajax/(?P<chemical>([A-Za-z0-9_-]+))/',
    #     ajax_views.chemical_gene_ajax,
    #     name="chemical-gene-ajax"),
    # url(r'^chemical-pathway-ajax/(?P<chemical>([A-Za-z0-9_-]+))/',
    #     ajax_views.chemical_pathway_ajax,
    #     name="chemical-pathway-ajax"),
    url(r'^chemical/(?P<chemical>([A-Za-z0-9_-]+))/',
        views.chemical,
        name="chemical"),
    url(r'^health-effect/(?P<pk>[0-9]+)/$',
            views.health_effect_redirect,
            name="health-effect-redirect"),
    url(r'^health-effect/(?P<slug>[a-zA-Z0-9-_]+)/$',
        views.health_effect,
        name="health-effect"),
    url(r'^organism/(?P<slug>[a-zA-Z0-9-_]+)/$',
        views.organism,
        name="organism"),
    url(r'^preparation/(?P<slug>[a-zA-Z0-9-_]+)/$',
        views.preparation,
        name="preparation"),
    url(r'^chemicals-list-api/$', views.chemicals_list_api, name="chemicals-list-api"),

]

database/urls.py
from django.conf.urls import url

from database import views

urlpatterns = [
    url(r'^database/', views.DatabaseView.as_view(), name="main"),
    url(r'^list-genes/letter/(?P<letter>[a-z])/page/(?P<page>\d+)', views.AllGenesByLetter.as_view(), name='all-genes-by-letter-with-page'),
    url(r'^list-genes/letter/(?P<letter>[a-z0-9])', views.AllGenesByLetter.as_view(), name='all-genes-by-letter'),
    url(r'^list-genes/page/(?P<page>\d+)', views.AllGenes.as_view(), name="all-genes"),
    url(r'^list-genes/', views.AllGenes.as_view(), name='list-genes'),

    url(r'^list-diseases/letter/(?P<letter>[a-z])/page/(?P<page>\d+)', views.AllDiseasesByLetter.as_view(), name='all-diseases-by-letter-with-page'),
    url(r'^list-diseases/letter/(?P<letter>[a-z0-9])', views.AllDiseasesByLetter.as_view(), name='all-diseases-by-letter'),
    url(r'^list-diseases/page/(?P<page>\d+)', views.AllDiseases.as_view(), name="all-diseases"),
    url(r'^list-diseases/', views.AllDiseases.as_view(), name='list-diseases'),

    url(r'^list-traits/letter/(?P<letter>[a-z])/page/(?P<page>\d+)', views.AllTraitsByLetter.as_view(), name='all-traits-by-letter-with-page'),
    url(r'^list-traits/letter/(?P<letter>[a-z0-9])', views.AllTraitsByLetter.as_view(), name='all-traits-by-letter'),
    url(r'^list-traits/page/(?P<page>\d+)', views.AllTraits.as_view(), name="all-traits"),
    url(r'^list-traits/', views.AllTraits.as_view(), name='list-traits'),

    url(r'^list-measurements/letter/(?P<letter>[a-z])/page/(?P<page>\d+)', views.AllMeasurementsByLetter.as_view(), name='all-measurements-by-letter-with-page'),
    url(r'^list-measurements/letter/(?P<letter>[a-z0-9])', views.AllMeasurementsByLetter.as_view(), name='all-measurements-by-letter'),
    url(r'^list-measurements/page/(?P<page>\d+)', views.AllMeasurements.as_view(), name="all-measurements"),
    url(r'^list-measurements/', views.AllMeasurements.as_view(), name='list-measurements'),

    url(r'^list-biological-process/page/(?P<page>\d+)', views.AllBiologicalProcesses.as_view(), name="all-biological-process"),
    url(r'^list-biological-process/', views.AllBiologicalProcesses.as_view(), name='list-biological-process'),

    url(r'^list-molecular-function/page/(?P<page>\d+)', views.AllMolecularFunctions.as_view(), name="all-molecular-function"),
    url(r'^list-molecular-function/', views.AllMolecularFunctions.as_view(), name='list-molecular-function'),

    url(r'^list-snps/page/(?P<page>\d+)', views.AllSnps.as_view(), name="all-snps"),
    url(r'^list-snps/', views.AllSnps.as_view(), name='list-snps'),

    url(r'^list-health-effects/letter/(?P<letter>[a-z])/page/(?P<page>\d+)', views.AllHealthEffectsByLetter.as_view(), name='all-health-effects-by-letter-with-page'),
    url(r'^list-health-effects/letter/(?P<letter>[a-z0-9])', views.AllHealthEffectsByLetter.as_view(), name='all-health-effects-by-letter'),
    url(r'^list-health-effects/page/(?P<page>\d+)/?$', views.AllHealthEffects.as_view(), name='all-health-effects'),
    url(r'^list-health-effects/?$', views.AllHealthEffects.as_view(), name='list-health_effects'),

    url(r'^list-chemicals/page/(?P<page>\d+)/?$', views.AllChemicals.as_view(), name='all-chemicals'),
    url(r'^list-chemicals/?$', views.AllChemicals.as_view(), name='list-chemicals'),

    url(r'^list-chemicals-categorized/(?P<category>natural-treatments|beneficial-substances|important-natural-compounds|popular-drugs|toxins|drug|obscure_chemicals)/page/(?P<page>\d+)/?$', views.AllChemicalsByCategory.as_view(), name='all-chemicals-categorized'),
    url(r'^list-chemicals-categorized/(?P<category>natural-treatments|beneficial-substances|important-natural-compounds|popular-drugs|toxins|drug|obscure_chemicals)/$', views.AllChemicalsByCategory.as_view(), name='list-chemicals-categorized'),

    url(r'^list-experiments/page/(?P<page>\d+)/$', views.ExperimentList.as_view(), name="list-experiments"),
    url(r'^list-experiments/$', views.ExperimentList.as_view(), name="list-experiments"),
]

decodify/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

from decodify.signup import SignupFreeView
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    url(r'^joes_office/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/signup_free/', SignupFreeView.as_view(), name="account_signup_free"),
    url(r'^hijack/', include('hijack.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'', include("genome.urls")),
    url(r'', include("chemical.urls", namespace="chemical")),
    url(r'', include("payment.urls", namespace="payment")),
    url(r'', include("guide.urls", namespace="guide")),
    url(r'', include("analysis.urls", namespace="analysis")),
    url(r'^fileapi/', include("fileapi.urls", namespace="fileapi")),
    url(r'^forum/', include("forum.urls", namespace="forum")),
    url(r'', include("experiment.urls", namespace="experiment")),
    url(r'', include("search.urls", namespace="search")),
    url(r'', include("database.urls", namespace="database")),
    url(r'', include('recommendation.urls', namespace="recommendation")),
    url(r'', include("affiliate.urls", namespace="affiliate")),
    url(r'^search/', include('haystack.urls')),
    url(r'', include("rating.urls", namespace="rating")),
    url(r'^social/', include('social.urls', namespace="social")),
    url(r'^api/v1/', include("api.urls", namespace="api")),
    url(r'^blog/', include('blog.urls', namespace="blog"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^api-docs/', include_docs_urls(title="Api docs")),
    ]

urlpatterns += [
    url(r'__debug__/', include(debug_toolbar.urls)),
]

handler500 = 'genome.views.handler500'
handler404 = 'genome.views.handler404'
handler403 = 'genome.views.handler403'

experiment/urls.py
from django.conf.urls import url

from experiment.views import experiment_details, experiment_ajax

urlpatterns = [
    url(r'^experiment_ajax/(?P<slug>.+)/', experiment_ajax, name="experiment_ajax"),
    url(r'^experiment_ajax/(?P<slug>.+)/', experiment_ajax, name="experiment_ajax"),
    url(r'^experiment/(?P<slug>.*)/$', experiment_details, name="details"),
]

database/models.py
from django.db import models

# Create your models here.

database/views.py
import string

from django.db.models import Count
from django.http import JsonResponse
from django.views.generic import ListView
from django.views.generic import TemplateView
from haystack.backends import SQ
from haystack.query import SearchQuerySet

from chemical.models import HealthEffect, Chemical
from chemical.models import SubstanceCategory
from experiment.models import Identification
from genome.mixins import AutocompleteSlugCatMixin, AutocompleteSlugTypeMixin, AutocompleteSlugMixin
from genome.models import Gene, Snp, DiseaseTrait, GeneOntology


class DatabaseView(TemplateView):
    template_name = 'database/database.html'


# Base classes for extending


class AllEnteries(ListView):
    paginate_by = 80
    allow_empty = False
    page_title = ''
    slug = ''

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['letters'] = [letter for letter in string.ascii_uppercase]
        context['title'] = self.page_title
        return context

    def get(self, request, *args, **kwargs):
        if request.is_ajax():
            query = request.GET.get('query', '')
            queryset = SearchQuerySet().models(self.model).filter(
                SQ(text__exact=query) | SQ(text__contains=query)
            )[:10]
            results = [item.text for item in queryset]
            data = {
                'query': query,
                'type': self.slug,
                "suggestions": results
            }
            return JsonResponse(data, safe=False)
        return super().get(request, *args, **kwargs)


class AllEnteriesByLetter(AllEnteries):

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        letter = self.kwargs['letter']
        if letter.isdigit():
            return queryset.filter(name__regex=r'^\d.+')
        return queryset.filter(name__startswith=letter)


class AllChemicals(AutocompleteSlugMixin, ListView):
    model = Chemical
    template_name = "database/list/chemical_list.html"
    paginate_by = 100
    context_object_name = 'chemicals'
    slug = 'chemical'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'All Chemicals'
        return context

    def get_queryset(self, **kwargs):
        queryset = super(AllChemicals, self).get_queryset(**kwargs)
        self.category = SubstanceCategory.objects.filter(slug='obscure_chemicals').first()
        return queryset.exclude(categories__in=list(self.category.get_family()))


class AllChemicalsByCategory(AllChemicals):
    template_name = "database/list/chemical_categorized_list.html"

    def get_context_data(self, **kwargs):
        context = super(AllChemicalsByCategory, self).get_context_data(**kwargs)
        context['category'] = self.category.slug
        context['title'] = self.category.name + ' Chemicals'
        return context

    def get_queryset(self, **kwargs):
        if self.kwargs['category'] == "obscure_chemicals":
            queryset = super(AllChemicals, self).get_queryset(**kwargs)
        else:
            queryset = super(AllChemicalsByCategory, self).get_queryset(**kwargs)
        self.category = SubstanceCategory.objects.filter(slug=self.kwargs['category']).first()
        qs = queryset.filter(categories__in=list(self.category.get_family())).annotate(cnt=Count('pk')).values('name', 'slug', 'display_as')
        return qs


class AllGeneOntology(AutocompleteSlugTypeMixin, AllEnteries):
    model = GeneOntology
    type = 'biological-process'
    context_object_name = 'biological_processes'
    page_title = 'All Biological Processes'

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        return queryset.filter(type=self.type)


# All database list


class AllGenes(AllEnteries):
    model = Gene
    template_name = 'database/list/genes.html'
    context_object_name = 'genes'
    page_title = 'All Genes'
    slug = 'gene'


class AllGenesByLetter(AllEnteriesByLetter):
    model = Gene
    template_name = 'database/list/genes_list_pages.html'
    context_object_name = 'genes'
    page_title = 'All Genes'
    slug = 'gene'


class AllSnps(AllEnteries):
    model = Snp
    template_name = "database/list/snps.html"
    context_object_name = 'snp_packs'
    page_title = 'All SNP Packs'
    slug = 'snp'


class AllTraits(AutocompleteSlugCatMixin, AllEnteries):
    model = DiseaseTrait
    template_name = 'database/list/traits.html'
    category = 'Trait'
    context_object_name = 'traits'
    page_title = 'All Traits'
    slug = 'trait'

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        return queryset.filter(category__name=self.category)


class AllTraitsByLetter(AllTraits):
    model = DiseaseTrait
    template_name = 'database/list/traits_list_pages.html'
    category = 'Trait'
    context_object_name = 'traits'
    slug = 'trait'

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        letter = self.kwargs['letter']
        if letter.isdigit():
            return queryset.filter(name__regex=r'^\d.+', category__name=self.category)
        return queryset.filter(name__startswith=letter, category__name=self.category)


class AllMeasurements(AllTraits):
    template_name = 'database/list/measurements.html'
    category = 'Measurement'
    context_object_name = 'measurements'
    page_title = 'All Measurements'
    slug = 'measurement'


class AllMeasurementsByLetter(AllTraitsByLetter):
    template_name = 'database/list/measurements_list_pages.html'
    category = 'Measurement'
    context_object_name = 'measurements'
    page_title = 'All Measurements'
    slug = 'measurement'


class AllDiseases(AllTraits):
    template_name = 'database/list/diseases.html'
    category = 'Disease'
    context_object_name = 'diseases'
    page_title = 'All Diseases'
    slug = 'disease'


class AllDiseasesByLetter(AllTraitsByLetter):
    template_name = 'database/list/diseases_list_pages.html'
    category = 'Disease'
    context_object_name = 'diseases'
    page_title = 'All Diseases'


class AllBiologicalProcesses(AllGeneOntology):
    template_name = 'database/list/biological_process_list.html'
    type = 'biological-process'
    context_object_name = 'biological_processes'
    page_title = 'All Biological Processes'


class AllMolecularFunctions(AllGeneOntology):
    template_name = 'database/list/molecular_function_list.html'
    type = 'molecular-function'
    context_object_name = 'molecular_function'
    page_title = 'All Molecular Functions'


class AllHealthEffects(AutocompleteSlugMixin, ListView):
    model = HealthEffect
    template_name = "database/list/healtheffect_list.html"
    paginate_by = 100
    allow_empty = False
    context_object_name = 'health_effects'
    slug = 'health-effect'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['letters'] = [letter for letter in string.ascii_uppercase]
        context['title'] = 'All Health Effects'
        return context


class AllHealthEffectsByLetter(AllHealthEffects):
    template_name = 'database/list/healtheffect_list_pages.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['letters'] = [letter for letter in string.ascii_uppercase]
        context['title'] = 'All Health Effects'
        return context

    def get_queryset(self, **kwargs):
        queryset = super().get_queryset(**kwargs)
        letter = self.kwargs['letter']
        if letter.isdigit():
            return queryset.filter(name__regex=r'^\d.+')
        return queryset.filter(name__startswith=letter)


class ExperimentList(AutocompleteSlugMixin, ListView):
    model = Identification
    template_name = "database/list/experiments.html"
    paginate_by = 80
    page_title = "All Experiments"
    slug = 'experiment'

    def get_context_data(self, **kwargs):
        context = super(ExperimentList, self).get_context_data(**kwargs)
        context['title'] = self.page_title
        return context

database/templates/database/list/chemical_categorized_list.html
{% extends "base_list.html" %}

{% load chemical_filters %}

{% block title %} <title>All {{ category }} Chemicals | page {{ page_obj.number }} | Genome Analysis</title> {% endblock %}

{% block autocomplete %}
    {% include 'autocomplete.html' with filter='chemical' autocomplete_id='autocomplete' %}
{% endblock %}


{% block items %}
    <div class="row" style="margin-top: 25px">
        {% for chunk in chemicals|chunk_queryset:paginator.per_page %}
            <div class="col-md-3">
                <ul>
                    {% for chemical in chunk %}
                        {% url 'chemical:chemical' chemical.slug as link %}
                        <li class="truncate"><a href="{{ link }}">{{ chemical.display_as|default:chemical.name|capfirst }}</a></li>
                    {% endfor %}
                </ul>
            </div>
        {% endfor %}
    </div>
{% endblock items %}

{% block pagination %}
    <div class="row">
        <nav aria-label="Page navigation">
            <ul class="pagination">

                {% if page_obj.has_previous %}
                    <li>
                        {% url 'database:all-chemicals-categorized' category page_obj.previous_page_number as prev_page_url %}
                        <a href="{{ prev_page_url }}" area-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for i in page_obj|page_range %}
                    <li {% if page_obj.number == i %} class="active" {% endif %}>
                        {% url 'database:all-chemicals-categorized' category i as page_url %}
                        <a href="{{ page_url }}">{{ i }}</a>
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li>
                        {% url 'database:all-chemicals-categorized' category page_obj.next_page_number as next_page_url %}
                        <a href="{{ next_page_url }}" area-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}

            </ul>
        </nav>
    </div>
{% endblock pagination %}

database/templates/database/list/chemical_list.html
{% extends "base_list.html" %}

{% load chemical_filters %}

{% block title %} <title>All Chemicals | page {{ page_obj.number }} | Genome Analysis</title> {% endblock %}

        {% block autocomplete %}
            {% include 'autocomplete.html' with filter='chemical' autocomplete_id='autocomplete' %}
        {% endblock %}

        {% block items %}
        <div class="row" style="margin-top: 25px">
            {% for chunk in chemicals|chunk_queryset:paginator.per_page %}
                <div class="col-md-3">
                    <ul>
                        {% for chemical in chunk %}
                            {% url 'chemical:chemical' chemical.slug as link %}
                            <li class="truncate"><a href="{{ link }}" >{{ chemical.display_name|title }}</a></li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>
        {% endblock items %}

        {% block pagination %}
        <div class="row">
            <nav aria-label="Page navigation">
                <ul class="pagination">

                {% if page_obj.has_previous %}
                    <li>
                        {% url 'database:all-chemicals' page_obj.previous_page_number as prev_page_url %}
                        <a href="{{ prev_page_url }}" area-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for i in page_obj|page_range %}
                    <li {% if page_obj.number == i %} class="active" {% endif %}>
                        {% url 'database:all-chemicals' i as page_url %}
                        <a href="{{ page_url }}">{{ i }}</a>
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li>
                        {% url 'database:all-chemicals' page_obj.next_page_number as next_page_url %}
                        <a href="{{ next_page_url }}" area-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}

                </ul>
            </nav>
        </div>
        {% endblock pagination %}

database/templates/database/list/diseases_list_pages.html
{% extends "base_list.html" %}

{% load genome_filters %}

{% block title %} <title>All Diseases | {{ request.resolver_match.kwargs.letter|upper }} |  page {{ page_obj.number }} | Genome Analysis</title> {% endblock %}

        {% block autocomplete %}
            {% include 'autocomplete.html' with filter='disease' autocomplete_id='autocomplete' %}
        {% endblock %}

        {% block letters %}
        <div class="row">
            <h3>
                {% for letter in letters %}
                    {% url 'database:all-diseases-by-letter' letter|lower as letter_url %}
                    <a href="{{ letter_url }}" {% if letter|lower == request.resolver_match.kwargs.letter %} style="text-decoration: underline;" {% endif %}>{{ letter }}</a>
                {% endfor %}
                {% url 'database:all-diseases-by-letter' '0' as numeric_url %}
                <a href="{{ numeric_url }}" {% if request.resolver_match.kwargs.letter.isdigit %} style="text-decoration: underline;" {% endif %}>[0-9]</a>
            </h3>
        </div>
        {% endblock letters %}
        
        {% block items %}
        <div class="row">
            {% for chunk in diseases|chunk_queryset:paginator.per_page %}
                <div class="col-md-3">
                    <ul>
                        {% for disease in chunk %}
                            {% url 'disease' disease.slug as link %}
                            <li  class="no-dotes truncate">
                                <a class="truncate"class="truncate" href="{{ link }}">{{ disease }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>
        {% endblock items %}

        {% block pagination %}
        <div class="row">
            <nav aria-label="Page navigation">
                <ul class="pagination">

                {% if page_obj.has_previous %}
                    <li>
                        {% url 'database:all-diseases-by-letter-with-page' request.resolver_match.kwargs.letter page_obj.previous_page_number as prev_page_url %}
                        <a href="{{ prev_page_url }}" area-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for i in page_obj|page_range %}
                    <li {% if page_obj.number == i %} class="active" {% endif %}>
                        {% url 'database:all-diseases-by-letter-with-page' request.resolver_match.kwargs.letter i as page_url %}
                        <a href="{{ page_url }}">{{ i }}</a>
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li>
                        {% url 'database:all-diseases-by-letter-with-page' request.resolver_match.kwargs.letter page_obj.next_page_number as next_page_url %}
                        <a href="{{ next_page_url }}" area-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}

                </ul>
            </nav>
        </div>
        {% endblock pagination %}

database/templates/database/list/experiments.html
{% extends "base_list.html" %}

{% load genome_filters %}

{% block title %} <title>All Experiments | page {{ page_obj.number }} | Genome Analysis</title> {% endblock %}

{% block autocomplete %}
    {% include 'autocomplete.html' with filter='identification' autocomplete_id='autocomplete' %}
{% endblock %}

{% block items %}
<div class="row" style="margin-top: 25px;">
    {% for chunk in object_list|chunk_queryset:paginator.per_page %}
        <div class="col-md-3">
            <ul>
                {% for item in chunk %}
                    {% url 'experiment:details' item.slug as link %}
                    <li class="no-dotes"><a href="{{ link }}">{{ item.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
</div>
{% endblock items %}

{% block pagination %}
<div class="row">
    <nav aria-label="Page navigation">
        <ul class="pagination">

        {% if page_obj.has_previous %}
            <li class="no-dotes">
                {% url "database:list-experiments" page_obj.previous_page_number as prev_page_url %}
                <a href="{{ prev_page_url }}" area-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        {% endif %}

        {% for i in page_obj|page_range %}
            <li {% if page_obj.number == i %} class="active" {% endif %}>
                {% url "database:list-experiments" i as page_url %}
                <a href="{{ page_url }}">{{ i }}</a>
            </li>
        {% endfor %}

        {% if page_obj.has_next %}
            <li>
                {% url "database:list-experiments" page_obj.next_page_number as next_page_url %}
                <a href="{{ next_page_url }}" area-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        {% endif %}

        </ul>
    </nav>
</div>
{% endblock pagination %}

database/templates/database/list/healtheffect_list_pages.html
{% extends "base_list.html" %}

{% load genome_filters %}

{% block title %} <title>All Health Effects | {{ request.resolver_match.kwargs.letter|upper }} |  page {{ page_obj.number }} | Genome Analysis</title> {% endblock %}

        {% block autocomplete %}
            {% include 'autocomplete.html' with filter='health_effect' autocomplete_id='autocomplete' %}
        {% endblock %}

        {% block letters %}
        <div class="row">
            <h3>
                {% for letter in letters %}
                    {% url 'database:all-health-effects-by-letter' letter|lower as letter_url %}
                    <a href="{{ letter_url }}" {% if letter|lower == request.resolver_match.kwargs.letter %} style="text-decoration: underline;" {% endif %}>{{ letter }}</a>
                {% endfor %}
                {% url 'database:all-health-effects-by-letter' '0' as numeric_url %}
                <a href="{{ numeric_url }}" {% if request.resolver_match.kwargs.letter.isdigit %} style="text-decoration: underline;" {% endif %}>[0-9]</a>
            </h3>
        </div>
        {% endblock letters %}
        
        {% block items %}
        <div class="row">
            {% for chunk in health_effects|chunk_queryset:paginator.per_page %}
                <div class="col-md-3">
                    <ul>
                        {% for health_effect in chunk %}
                            {% url 'chemical:health-effect' health_effect.slug as link %}
                            <li class="no-dotes truncate">
                                <a href="{{ link }}">{{ health_effect }}</a>
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
        </div>
        {% endblock items %}

        {% block pagination %}
        <div class="row">
            <nav aria-label="Page navigation">
                <ul class="pagination">

                {% if page_obj.has_previous %}
                    <li>
                        {% url 'database:all-health-effects-by-letter-with-page' request.resolver_match.kwargs.letter page_obj.previous_page_number as prev_page_url %}
                        <a href="{{ prev_page_url }}" area-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                {% endif %}

                {% for i in page_obj|page_range %}
                    <li {% if page_obj.number == i %} class="active" {% endif %}>
                        {% url 'database:all-health-effects-by-letter-with-page' request.resolver_match.kwargs.letter i as page_url %}
                        <a href="{{ page_url }}">{{ i }}</a>
                    </li>
                {% endfor %}

                {% if page_obj.has_next %}
                    <li>
                        {% url 'database:all-health-effects-by-letter-with-page' request.resolver_match.kwargs.letter page_obj.next_page_number as next_page_url %}
                        <a href="{{ next_page_url }}" area-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                {% endif %}

                </ul>
            </nav>
        </div>
        {% endblock pagination %}