analysis/urls.py
from django.conf.urls import url

from analysis.views import (
    personalized_health_report,
    personalized_health_pdf_report,
    create_system,
    delete_system,
    edit_system,
)
from .autocomplete_views import SymptomAutocomplete, SymptomsForeignAutocompleteView, symptoms_list_api

urlpatterns = [
    url('^personalized-health-report/$', personalized_health_report, name="personalized-health-report"),
    url('^personalized-health-pdf-report/$', personalized_health_pdf_report, name="personalized-health-pdf-report"),
    url('^create-system/$', create_system, name="create-system"),
    url('^delete-system/(?P<id>\d+)/$', delete_system, name="delete-system"),
    url('^edit-system/(?P<id>\d+)/$', edit_system, name="edit-system"),

    url(r'^autocomplete/symptoms/$', SymptomAutocomplete.as_view(), name="autocomplete-symptoms"),
    url(r'^symptoms-foreign-autocomplete/$', SymptomsForeignAutocompleteView.as_view(), name="autocomplete-symptoms-foreign"),
    url(r'^symptoms-list-api/$', symptoms_list_api, name="symptoms-list-api"),
]

api/urls.py
from api import views

from rest_framework import routers

router = routers.SimpleRouter()

router.register(r'chemical', views.ChemicalView, "chemical")

urlpatterns = router.urls

decodify/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

from decodify.signup import SignupFreeView
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    url(r'^joes_office/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/signup_free/', SignupFreeView.as_view(), name="account_signup_free"),
    url(r'^hijack/', include('hijack.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'', include("genome.urls")),
    url(r'', include("chemical.urls", namespace="chemical")),
    url(r'', include("payment.urls", namespace="payment")),
    url(r'', include("guide.urls", namespace="guide")),
    url(r'', include("analysis.urls", namespace="analysis")),
    url(r'^fileapi/', include("fileapi.urls", namespace="fileapi")),
    url(r'^forum/', include("forum.urls", namespace="forum")),
    url(r'', include("experiment.urls", namespace="experiment")),
    url(r'', include("search.urls", namespace="search")),
    url(r'', include("database.urls", namespace="database")),
    url(r'', include('recommendation.urls', namespace="recommendation")),
    url(r'', include("affiliate.urls", namespace="affiliate")),
    url(r'^search/', include('haystack.urls')),
    url(r'', include("rating.urls", namespace="rating")),
    url(r'^social/', include('social.urls', namespace="social")),
    url(r'^api/v1/', include("api.urls", namespace="api")),
    url(r'^blog/', include('blog.urls', namespace="blog"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^api-docs/', include_docs_urls(title="Api docs")),
    ]

urlpatterns += [
    url(r'__debug__/', include(debug_toolbar.urls)),
]

handler500 = 'genome.views.handler500'
handler404 = 'genome.views.handler404'
handler403 = 'genome.views.handler403'

analysis/models.py
from ckeditor.fields import RichTextField
from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.db import models

from django.db.models.signals import m2m_changed
from django_extensions.db.fields import AutoSlugField

from chemical.models import Chemical
from genome.models import Gene, GenePack

from django.dispatch import receiver
from genericm2m.models import RelatedObjectsDescriptor


class Symptom(models.Model):
    name = models.CharField(max_length=255)
    slug = AutoSlugField(populate_from="name", max_length=255)
    selfhacked_link = models.CharField(max_length=255, blank=True)
    related_objects = RelatedObjectsDescriptor()

    def __str__(self):
        return self.name


class SystemSymptoms(models.Model):
    system = models.ForeignKey("System", on_delete=models.CASCADE, null=False)
    symptom = models.ForeignKey("Symptom", on_delete=models.CASCADE, null=False)
    weight = models.FloatField(default=0.0, null=False, blank=False)

    def __str__(self):
        return "%s <%s> %s" % (self.system, self.weight, self.symptom,)

    class Meta:
        verbose_name = "System Symptom"
        verbose_name_plural = "System Symptoms"


class System(models.Model):
    name = models.CharField(max_length=255, blank=False, null=False)
    short_name = models.CharField(max_length=255, blank=True, null=True)
    slug = AutoSlugField(populate_from="name", max_length=255, blank=False, null=False)
    threshold = models.FloatField(default=0, null=False, blank=False)
    description = RichTextField(null=True, blank=True)
    threshold_description = RichTextField(null=True, blank=True)
    symptoms = models.ManyToManyField(Symptom, blank=False, through=SystemSymptoms)
    genes = models.ManyToManyField(Gene, blank=True)
    chemicals = models.ManyToManyField(Chemical, blank=True)
    gene_packs = models.ManyToManyField(GenePack, blank=True)
    user = models.ForeignKey(User, default=1, related_name='systems')

    def __str__(self):
        return self.name


@receiver(m2m_changed, sender=System.gene_packs.through)
def add_genes_from_gene_pack(instance, action, pk_set, **kwargs):
    if action == 'pre_remove':
        genes_to_remove = Gene.objects.filter(related_gene_pack__id__in=pk_set)
        instance.genes.remove(*list(genes_to_remove))
    if action == 'pre_add':
        genes_to_add = Gene.objects.filter(related_gene_pack__id__in=pk_set)
        instance.genes.add(*list(genes_to_add))

analysis/forms.py
from dal import autocomplete
from django import forms

from analysis.models import System, Symptom
from chemical.models import Chemical, HealthEffect
from experiment.models import Identification
from genome.models import Gene, Snp, DiseaseTrait


class SystemAdminForm(forms.ModelForm):
    class Meta:
        model = System
        fields = '__all__'
        widgets = {
            "genes": autocomplete.ModelSelect2Multiple(url="genome_gene_autocomplete"),
            'chemicals': autocomplete.ModelSelect2Multiple(url='chemical:chemical-autocomplete'),
            'threshold_symptoms': autocomplete.ModelSelect2Multiple(url='analysis:autocomplete-symptoms'),
        }


class SymptomAdminInlineForm(forms.ModelForm):
    class Meta:
        model = Symptom
        fields = '__all__'
        widgets = {
            'symptom': autocomplete.Select2(),
        }


class ForeignObjectForm(autocomplete.FutureModelForm):
    related_objects = autocomplete.GenericM2MQuerySetSequenceField(
        queryset=autocomplete.QuerySetSequence(
            Gene.objects.all(),
            Chemical.objects.exclude(categories__id=51).all(),
            DiseaseTrait.objects.all(),
            Snp.objects.all(),
            HealthEffect.objects.all(),
            Identification.objects.all(),
        ),
        required=False,
        widget=autocomplete.QuerySetSequenceSelect2Multiple(
            url='analysis:autocomplete-symptoms-foreign',
        ),
    )

    class Meta:
        model = Symptom
        fields = ('name', 'related_objects', 'selfhacked_link')


class CreateSystemForm(forms.ModelForm):

    class Meta:
        model = System
        fields = [
            'name',
            'short_name',
            'threshold',
            'description',
            'threshold_description',
            'genes',
            'chemicals',
        ]

analysis/views.py
import pdfkit

from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.urlresolvers import reverse
from django.db.models import Count
from django.http import FileResponse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.template.loader import get_template
from django.contrib import messages
from django.shortcuts import render

from analysis.forms import CreateSystemForm
from analysis.models import System, Symptom, SystemSymptoms
from analysis.helpers import get_recomendations_for_system, get_systems_queryset
from analysis.templatetags.analysis_filters import is_system_threshold_reached
from genome.helpers import get_potentially_problematic_genes
from genome.models import Gene


@login_required
def personalized_health_report(request):
    queryset = get_systems_queryset(request)

    if not queryset:
        return render(request, "analysis/personalized_health_report.html")

    paginator = Paginator(queryset, 1)

    page = request.GET.get('page')
    try:
        system_page = paginator.page(page)
    except PageNotAnInteger:
        system_page = paginator.page(1)
    except EmptyPage:
        system_page = paginator.page(paginator.num_pages)

    symptoms_list = []
    if system_page:
        system_symptoms = set(system_page.object_list[0].symptoms.all().values_list('name', flat=True))
        user_symptoms = set(request.user.user_profile.symptoms.all().values_list('name', flat=True))
        symptoms_list = system_symptoms.intersection(user_symptoms)

    recommendations = get_recomendations_for_system(system_page.object_list[0])

    potentially_problematic_genes = get_potentially_problematic_genes(request.user)
    bad_genes = Gene.objects.filter(snps__id__in=potentially_problematic_genes).annotate(
        gene_cnt=Count('id')).values_list('id', flat=True)
    # bad_genes = set([gene.id for snp in potentially_problematic_genes for gene in snp.genes.all()])
    system_bad_genes = system_page.object_list[0].genes.filter(id__in=bad_genes)

    return render(request, "analysis/personalized_health_report.html", {
        "queryset": queryset,
        "system": system_page,
        "symptoms_list": symptoms_list,
        "recommendations": recommendations,
        "system_bad_genes": system_bad_genes,
    })


@login_required
def personalized_health_pdf_report(request):
    queryset = get_systems_queryset(request)
    potentially_problematic_genes = get_potentially_problematic_genes(request.user)
    user_symptoms = set(request.user.user_profile.symptoms.all().values_list('name', flat=True))
    bad_genes = Gene.objects.filter(snps__id__in=potentially_problematic_genes).annotate(
        gene_cnt=Count('id')).values_list('id', flat=True)

    systems = []
    for system in queryset:
        data = {}

        system_symptoms = set(system.symptoms.all().values_list('name', flat=True))
        symptoms_list = system_symptoms.intersection(user_symptoms)
        system_bad_genes = system.genes.filter(id__in=bad_genes)
        recommendations = get_recomendations_for_system(system)

        data['system'] = system
        data['recommendations'] = recommendations
        data['symptoms_list'] = symptoms_list
        data['system_bad_genes'] = system_bad_genes
        systems.append(data)

    if request.GET.get("pdf"):
        template = get_template('analysis/personalized_health_report_pdf.html')
        context = {
            "systems": systems,
            "request": request,
        }
        html = template.render(context)
        pdf_name = '/tmp/personalized_health_report-%s.pdf' % request.user.pk
        options = {
            'page-size': 'A4',
            'encoding': "UTF-8",
            'margin-top': 15,
            'margin-bottom': 15,
            'zoom': 1
        }
        pdfkit.from_string(html, pdf_name, options=options)
        response = FileResponse(open(pdf_name, 'rb'), content_type='application/octet-stream')
        response['Content-Disposition'] = 'attachment; filename="personalized_health_report.pdf"'
        return response

    return render(request, "analysis/personalized_health_report_pdf.html", {
        "systems": systems,
    })


@login_required
def create_system(request):
    query_set_symptoms = Symptom.objects.all()
    form = CreateSystemForm()
    if request.method == 'POST':
        form = CreateSystemForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.user = request.user
            instance.save()
            symptoms = zip(request.POST.getlist('symptoms[]'), request.POST.getlist('weights[]'))
            for symptom, weight in symptoms:
                if int(weight) <= 0:
                    continue
                SystemSymptoms.objects.create(
                    system_id=instance.id,
                    symptom_id=symptom,
                    weight=weight
                )
            form.save_m2m()
            messages.success(request, "System {}. Has been created.".format(instance.name))
            return HttpResponseRedirect(reverse('analysis:personalized-health-report'))

    return render(request, "analysis/create-system.html", {
        'form': form,
        'query_set_symptoms': query_set_symptoms
    })


@login_required
def edit_system(request, id):
    instance = get_object_or_404(System, id=id)
    query_set_symptoms = Symptom.objects.all()
    form = CreateSystemForm(instance=instance)
    if request.method == 'POST':
        form = CreateSystemForm(request.POST, instance=instance)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save()
            symptoms = zip(request.POST.getlist('symptoms[]'), request.POST.getlist('weights[]'))
            SystemSymptoms.objects.filter(system=instance).delete()
            for symptom, weight in symptoms:
                if int(weight) <= 0:
                    continue
                SystemSymptoms.objects.create(
                    system_id=instance.id,
                    symptom_id=symptom,
                    weight=weight
                )
            form.save_m2m()
            messages.success(request, "System {}. Has been modified.".format(instance.name))
            return HttpResponseRedirect(reverse('analysis:personalized-health-report'))
    return render(request, 'analysis/edit-system.html', {
        'form': form,
        'instance': instance,
        'symptoms': SystemSymptoms.objects.filter(system=instance),
        'query_set_symptoms': query_set_symptoms,
    })


@login_required
def delete_system(request, id):
    instance = get_object_or_404(System, pk=id)
    if request.user == instance.user:
        instance.delete()
        messages.success(request, "System {}. Has been deleted.".format(instance.name))
    return HttpResponseRedirect(reverse('analysis:personalized-health-report'))

analysis/templates/analysis/create-system.html
{% extends "base.html" %}

{% load staticfiles %}
{% load analysis_filters %}
{% load keyword_link %}
{% load demouser %}

{% block title %} <title>Create a System | SelfDecode | Genome Analysis</title> {% endblock %}

{% block head %}
    {{ block.super }}
    <link rel="stylesheet" type="text/css" href="{% static 'chosen/chosen.min.css' %}" />
    <link rel="stylesheet" href="{% static 'genome/css/recomendations.css' %}" type="text/css" />
    <style>
    .delete-btn:hover{
        color: #E7573E;
    }
    </style>
{% endblock %}

{% block breadcrumbs %}
    <ol id="decodify_breadcrumbs" class="breadcrumb">
        <li class="item-home"><a class="bread-link bread-home" href="/" title="Home">Home</a></li>
        <li class="item-home"><a class="bread-link bread-home" href="{% url "dashboard" %}" title="Home">User</a></li>
        <li class="item-home">
            <a class="bread-link bread-home" href="{% url "analysis:personalized-health-report" %}" title="Home">
                Personalized Health Report
            </a>
        </li>
        <li class="item-current item-3602"><strong class="bread-current bread-3602">Create System</strong></li>
    </ol>
{% endblock %}

{% block page_title %}
     Personalized Health Report
    &nbsp;
    {% if queryset %}
        <a href="{% url 'analysis:personalized-health-pdf-report' %}?pdf=true" title="Download report as a PDF file">
            <i class="glyphicon glyphicon-download-alt"></i>
        </a>
    {% endif %}
{% endblock %}

{% block content %}
        <div class="section">
            <div class="container">
                {% if not user|is_demouser %}
                <h1>Create a system</h1>
                <form class="form-horizontal" method="post">
                    {% csrf_token %}

                    {% if form.errors %}
                        <div class="alert alert-danger">
                            <button type="button" class="close" data-dismiss="alert">×</button>
                            {% for field in form %}
                                {% if field.errors %}
                                    <li>{{ field.label }}: {{ field.errors|striptags }}</li>
                                {% endif %}
                            {% endfor %}
                        </div>
                    {% endif %}

                    <div class="form-group">
                        <div class="col-sm-9">
                            <label class="control-label" for="system-name">System Name:</label>
                            <input type="text" id="system-name" class="form-control" name="name" minlength=2
                                   maxlength=70 required>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9">
                            <label class="control-label" for="system-short-name">Short Name:</label>
                            <input type="text" id="system-short-name" class="form-control" name="short_name" minlength=2
                                   maxlength=20>
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-sm-9">
                            <label class="control-label" for="system-name">Threshold:</label>
                            <input type="number" id="system-name" class="form-control" name="threshold" required min="1">
                        </div>
                    </div>

                    <div class="form-group">
                        <label style="margin-left: 15px" class="control-label" for="description">Description:</label>
                        <div class="col-sm-12">
                            {{ form.description }}
                        </div>
                    </div>

                    <div class="form-group">
                        <label style="margin-left: 15px" class="control-label" for="threshold-description">Threshold Description:</label>
                        <div class="col-sm-12">
                            {{ form.threshold_description }}
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h3 class="panel-title">Select Genes</h3>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <select name="genes" data-placeholder="Type here to select genes"
                                                multiple class="chosen-select genes" style="display: none;">
                                        </select>
                                        <div class="hidden-tags"></div>
                                    </div>
                                </div>
                            </div><!-- /.panel-body -->
                            <div class="panel-footer"></div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h3 class="panel-title">Select Substances</h3>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <div class="col-sm-12">
                                        <select
                                                data-placeholder="Type here to select Substances."
                                                multiple
                                                name="chemicals"
                                                class="chosen-select chemicals"
                                                style="display: none;">
                                        </select>
                                        <div class="chem-button pull-right"></div>
                                    </div>
                                </div>
                            </div><!-- /.panel-body -->
                            <div class="panel-footer"></div>
                        </div>
                    </div>

                    <div class="col-sm-12">
                        <div class="panel panel-info">
                            <div class="panel-heading">
                                <h3 class="panel-title">System Symptoms</h3>
                            </div>
                            <div class="panel-body">
                                <div class="row">
                                    <table class="table symptom-table">
                                        <thead>
                                            <tr>
                                                <th width="40%">Symptom</th>
                                                <th>Weight</th>
                                                <th></th>
                                            </tr>
                                        </thead>
                                        <tbody>
                                            <tr>
                                                <td>
                                                    <div class="chosen-search">
                                                        <select
                                                            data-placeholder="Type a symptom name..."
                                                            name="symptoms[]"
                                                            class="chosen-select symptoms">
                                                            {% for item in query_set_symptoms %}
                                                                <option value="{{ item.id }}">
                                                                    {{ item.name|title }}
                                                                </option>
                                                            {% endfor %}
                                                        </select>
                                                    </div>
                                                </td>
                                                <td>
                                                    <input
                                                        class="form-control"
                                                        type="number"
                                                        style="width: 20%"
                                                        value="1"
                                                        name="weights[]"
                                                        min="1">
                                                </td>
                                                <td style="vertical-align: middle;">
                                                    <span
                                                        class="glyphicon glyphicon-remove text-muted delete-btn"
                                                        aria-hidden="true"
                                                        title="Delete row">
                                                    </span>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>
                                    <div class="row">
                                        <div class="col-sm-3" style="margin-left: 5px">
                                        <span
                                            class="glyphicon glyphicon-plus text-success"
                                            aria-hidden="true">
                                        </span>
                                        <a href="" class="add-symptom-btn">Add another symptom.</a>
                                        </div>
                                    </div>
                                </div>

                            </div><!-- /.panel-body -->
                            <div class="panel-footer"></div>
                        </div>
                    </div>

                    <button type="submit" class="btn btn-info pull-right">Create</button>
                </form>
                {% else %}
                    <h3>You are not allowed to view this page.</h3>
                {% endif %}
            </div>
        </div>
{% endblock %}

{% block scripts %}
    <script type="html/template" id="symptom-row">
        <tr>
            <td>
                <div class="chosen-search">
                    <select
                        data-placeholder="Type a symptom name..."
                        name="symptoms[]"
                        class="chosen-select symptoms">
                        {% for item in query_set_symptoms %}
                            <option value="{{ item.id }}">
                                {{ item.name|title }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
            </td>
            <td>
                <input class="form-control" name="weights[]" type="number" style="width: 20%" min="1" value="1">
            </td>
            <td style="vertical-align: middle;">
                <span
                    class="glyphicon glyphicon-remove text-muted delete-btn"
                    aria-hidden="true"
                    title="Delete row">
                </span>
            </td>
        </tr>
    </script>

    <script type="text/javascript" src="/static/ckeditor/ckeditor/ckeditor.js"></script>
    <script type="text/javascript" src="/static/ckeditor/ckeditor-init.js" ></script>
    <script src="{% static 'chosen/chosen.jquery.min.js' %}"></script>
    <script src="{% static 'chosen/chosen.ajaxaddition.jquery.js' %}"></script>
    <script src="{% static 'js/utils.js' %}"></script>
    <script src="{% static 'analysis/create-symptom.js' %}"></script>
{% endblock %}