api/urls.py
from api import views

from rest_framework import routers

router = routers.SimpleRouter()

router.register(r'chemical', views.ChemicalView, "chemical")

urlpatterns = router.urls

decodify/urls.py
import debug_toolbar
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

from decodify.signup import SignupFreeView
from rest_framework.documentation import include_docs_urls

urlpatterns = [
    url(r'^joes_office/', admin.site.urls),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^accounts/signup_free/', SignupFreeView.as_view(), name="account_signup_free"),
    url(r'^hijack/', include('hijack.urls')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'', include("genome.urls")),
    url(r'', include("chemical.urls", namespace="chemical")),
    url(r'', include("payment.urls", namespace="payment")),
    url(r'', include("guide.urls", namespace="guide")),
    url(r'', include("analysis.urls", namespace="analysis")),
    url(r'^fileapi/', include("fileapi.urls", namespace="fileapi")),
    url(r'^forum/', include("forum.urls", namespace="forum")),
    url(r'', include("experiment.urls", namespace="experiment")),
    url(r'', include("search.urls", namespace="search")),
    url(r'', include("database.urls", namespace="database")),
    url(r'', include('recommendation.urls', namespace="recommendation")),
    url(r'', include("affiliate.urls", namespace="affiliate")),
    url(r'^search/', include('haystack.urls')),
    url(r'', include("rating.urls", namespace="rating")),
    url(r'^social/', include('social.urls', namespace="social")),
    url(r'^api/v1/', include("api.urls", namespace="api")),
    url(r'^blog/', include('blog.urls', namespace="blog"))
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += [
        url(r'^api-docs/', include_docs_urls(title="Api docs")),
    ]

urlpatterns += [
    url(r'__debug__/', include(debug_toolbar.urls)),
]

handler500 = 'genome.views.handler500'
handler404 = 'genome.views.handler404'
handler403 = 'genome.views.handler403'

experiment/urls.py
from django.conf.urls import url

from experiment.views import experiment_details, experiment_ajax

urlpatterns = [
    url(r'^experiment_ajax/(?P<slug>.+)/', experiment_ajax, name="experiment_ajax"),
    url(r'^experiment_ajax/(?P<slug>.+)/', experiment_ajax, name="experiment_ajax"),
    url(r'^experiment/(?P<slug>.*)/$', experiment_details, name="details"),
]

experiment/models.py
from django.db import models

# Create your models here.
from django_extensions.db.fields import AutoSlugField

from chemical.models import Organism
from genome.models import Gene, DiseaseTrait


class Identification(models.Model):
    name = models.CharField(max_length=512, null=True, blank=True)
    slug = AutoSlugField(populate_from='name')
    title = models.CharField(max_length=512, null=True, blank=True)
    factor_name = models.CharField(max_length=512, null=True, blank=True)
    factor_type = models.CharField(max_length=512, null=True, blank=True)
    pub_med_id = models.CharField(max_length=512, null=True, blank=True)
    publication_title = models.TextField(default='', null=True, blank=True)
    publication_authors = models.TextField(default='', null=True, blank=True)
    protocol_name = models.TextField(default='', null=True, blank=True)
    protocol_description = models.TextField(default='', null=True, blank=True)
    organism_name = models.CharField(max_length=500, null=True, blank=True)
    organism = models.ForeignKey(Organism, null=True, blank=True)

    def __str__(self):
        return self.name


class Configuration(models.Model):
    identification = models.ForeignKey(Identification)
    contrast = models.CharField(max_length=500)
    name = models.CharField(max_length=500)
    disease_name = models.CharField(max_length=500, null=True, blank=True)
    disease = models.ForeignKey(DiseaseTrait, null=True, blank=True)
    condition = models.CharField(max_length=512, null=True, blank=True)
    comparison = models.CharField(max_length=512, null=True, blank=True)


class Analytics(models.Model):
    gene_name = models.CharField(max_length=512)
    gene = models.ForeignKey(Gene, null=True, blank=True)
    design_element = models.CharField(max_length=512)
    configuration = models.ForeignKey(Configuration)
    p_value = models.DecimalField(null=True, blank=True, max_digits=15, decimal_places=10)
    t_statistic = models.DecimalField(null=True, blank=True, max_digits=15, decimal_places=10)
    log2fold = models.DecimalField(null=True, blank=True, max_digits=15, decimal_places=10)

experiment/views.py
from django.core.paginator import PageNotAnInteger
from django.core.paginator import Paginator, EmptyPage
from django.db.models import Count
from django.db.models import F
from django.db.models import Max, Min
from django.db.models import QuerySet
from django.http import JsonResponse
from django.http import response
from django.shortcuts import render
from django.template import Context
from django.template.loader import get_template
from django.views.generic import DetailView
from django.views.generic import ListView

from decodify.aggregators import JsonAgg, ArrayAgg
from experiment.models import Identification, Analytics
from genome.mixins import AutocompleteSlugMixin


class ExperimentDetails(DetailView):
    model = Identification
    template_name = "experiment/details.html"

    def get_queryset(self):
        query_set = super(ExperimentDetails, self).get_queryset().prefetch_related(
            "configuration_set", "configuration_set__analytics_set"
        )
        return query_set

    def get_context_data(self, **kwargs):
        context = super(ExperimentDetails, self).get_context_data(**kwargs)
        context['min_positive'] = self.queryset.filter(configuration_set__analytics_set__log2fold__gte=0).aggregate(Min('configuration_set__analytics_set__log2fold'))
        context['max_positive'] = self.queryset.filter(configuration_set__analytics_set__log2fold__gte=0).aggregate(Max('configuration_set__analytics_set__log2fold'))
        context['min_negative'] = self.queryset.filter(configuration_set__analytics_set__log2fold__lte=0).aggregate(Min('configuration_set__analytics_set__log2fold'))
        context['max_negative'] = self.queryset.filter(configuration_set__analytics_set__log2fold__lte=0).aggregate(Max('configuration_set__analytics_set__log2fold'))
        return context


def experiment_ajax(request, slug):
    query_set = Identification.objects.filter(slug=slug)
    analytics = Analytics.objects.filter(configuration__identification=query_set).values(
        "gene_name", "gene__name"
    ).annotate(
        log2folds=JsonAgg("configuration_id", "log2fold"),
    ).extra(
        select={"ordering": "abs(log2fold)"}).order_by('-ordering')
    context = {
        'min_positive': query_set.filter(configuration__analytics__log2fold__gte=0).aggregate(
            Min('configuration__analytics__log2fold'))["configuration__analytics__log2fold__min"],
        'max_positive': query_set.filter(configuration__analytics__log2fold__gte=0).aggregate(
            Max('configuration__analytics__log2fold'))["configuration__analytics__log2fold__max"],
        'min_negative': query_set.filter(configuration__analytics__log2fold__lte=0).aggregate(
            Min('configuration__analytics__log2fold'))["configuration__analytics__log2fold__min"],
        'max_negative': query_set.filter(configuration__analytics__log2fold__lte=0).aggregate(
            Max('configuration__analytics__log2fold'))["configuration__analytics__log2fold__max"],
        'slicer': ":%s" % query_set.get().configuration_set.count(),
        'configurations': query_set.get().configuration_set.values("id"),
    }
    page = request.GET.get("page")
    paginator = Paginator(analytics, 10)
    template = get_template('experiment/partials/_details_table_body.html')

    try:
        current_page = paginator.page(page)
    except PageNotAnInteger:
        current_page = paginator.page(1)
    except EmptyPage:
        current_page = paginator.page(paginator.num_pages)

    if current_page.has_next():
        has_next = True
        next_page_number = current_page.next_page_number()
    else:
        next_page_number = current_page.paginator.num_pages
        has_next = False
    context = Context({
        "analytics": current_page.object_list,
        "context": context
    })
    return JsonResponse({
        'paginator': {
            'has_next': has_next,
            'next_page_number': next_page_number,
        },
        'data': template.render(context)
    })


def experiment_details(request, slug):
    query_set = Identification.objects.prefetch_related(
        "configuration_set"
    ).filter(slug=slug)

    analytics = Analytics.objects.filter(configuration__identification=query_set).values(
        "gene_name", "gene__name"
    ).annotate(
        log2folds=JsonAgg("configuration_id", "log2fold"),
    ).extra(
        select={"ordering": "abs(log2fold)"}).order_by('-ordering')
    context = {
        'min_positive': query_set.filter(configuration__analytics__log2fold__gte=0).aggregate(
            Min('configuration__analytics__log2fold'))["configuration__analytics__log2fold__min"],
        'max_positive': query_set.filter(configuration__analytics__log2fold__gte=0).aggregate(
            Max('configuration__analytics__log2fold'))["configuration__analytics__log2fold__max"],
        'min_negative': query_set.filter(configuration__analytics__log2fold__lte=0).aggregate(
            Min('configuration__analytics__log2fold'))["configuration__analytics__log2fold__min"],
        'max_negative': query_set.filter(configuration__analytics__log2fold__lte=0).aggregate(
            Max('configuration__analytics__log2fold'))["configuration__analytics__log2fold__max"],
        'slicer': ":%s" % query_set.get().configuration_set.count(),
        'configurations': query_set.get().configuration_set.values("id"),
    }
    return render(request, "experiment/details.html", {
        "object": query_set.get(),
        "context": context,
        "analytics": analytics[:10]
    })

experiment/templates/experiment/details.html
{% extends "base.html" %}

{% load staticfiles %}
{% load experiment_tags %}

{% block title %} <title>{{ object.name|upper }} | SelfDecode | Genome Analysis</title> {% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static "experiment/details.css" %}">
{% endblock %}

{% block breadcrumbs %}
    <ol id="decodify_breadcrumbs" class="breadcrumb">
        <li class="item-home"><a class="bread-link bread-home" href="/" title="Home">Home</a></li>
        <li class="item-cat item-custom-post-type-gene">
            <a class="bread-cat bread-custom-post-type-gene" href="#" title="Genes">
                Experiments
            </a>
        </li>
        <li class="item-current item-custom-post-type-gene">
            <strong class="bread-current bread-archive">
                {{ object.name|upper }}
            </strong>
        </li>
    </ol>
{% endblock %}

{% block page_title %}
    {{ object.name|upper }}
    {% if user.is_staff %}
        <a href="{% url "admin:experiment_identification_change" object.pk %}"> Edit</a>
    {% endif %}
{% endblock %}

{% block content %}

    <div class="container">
        <div id="primary" class="content-area">
            <main id="main" class="site-main" role="main">
                <h3 style="margin-bottom: 50px;">{{ object.title }}</h3>
{% comment %}

                <h4>Publication title:</h4>
                <p>{{ object.publication_title }}</p>

                <h4>Publication authors:</h4>
                <p>{{ object.publication_authors }}</p>

                <h4>Protocol names:</h4>
                <p>{{ object.protocol_name }}</p>

                <h4>Protocol description:</h4>
                <p>{{ object.protocol_description|safe }}</p>
{% endcomment %}
                {% include 'genome/partials/advertisement.html' %}
                <div class="col-md-8 col-md-offset-2">
                    <table class="table table-bordered experiment-table">
                        <thead class="bg-default">
                            <tr>
                                <th colspan="2" class="centered" style="height: 160px;">
{#                                    <button class="btn btn-default">Display log<sub>2</sub>-fold change</button>#}
                                </th>
                                {% for conf in object.configuration_set.all %}
                                    <th rowspan="2">
                                        <span class="vertical-text">{{ conf.name|truncatechars:"20" }}</span>
                                    </th>
                                {% endfor %}
                            </tr>
                            <tr>
                                <th class="gene-column">Gene</th>
                                <th>log<sub>2</sub>-fold change</th>
                            </tr>
                        </thead>
                        <tbody id="experiment-body">
                        {% include "experiment/partials/_details_table_body.html" %}
                        {% comment %}{% for analytic in analytics.all %}
                            <tr>
                                <td>
                                    <a {% if analytic.gene %} href="{{ analytic.gene.name }}"{% else %}
                                                              class="disabled"{% endif %}>{{ analytic.gene_name }}</a>
                                </td>
                            <td>{{ analytic.log2folds|max_log2fold|floatformat:1  }}</td>

{#                                <td>{{ analytic.log2fold|floatformat:1 }}</td>#}
                                {% for log2fold in analytic.log2folds|slice:context.slicer %}
                                    <td style="background:
                                            {% if log2fold >= 0 %}
                                                {% colour_saturation "red" context.min_positive context.max_positive log2fold %}
                                            {% else %}
                                                {% colour_saturation "blue" context.max_negative context.min_negative log2fold %}
                                            {% endif %}">
                                        <div class="gxaShowCell">
                                            {{ log2fold|floatformat:1 }}
                                        </div>
                                    </td>
                                {% endfor %}
                            </tr>
                        {% endfor %}{% endcomment %}
                        </tbody>
                    </table>
                    <div class="row">
                        <button id="more-experiments"
                                style="margin-bottom: 20px;"
                                class="btn btn-default center-block"
                                type="button"
                                data-url="{% url "experiment:experiment_ajax" object.slug %}"
                                data-type="increase"
                        >Load more
                        </button>
                    </div>
                </div>
            </main>
        </div>
    </div>
{% endblock %}


{% block scripts %}
    {{ block.super }}
    <script>
        $(document).ready(function () {
            var page = 2;
            $('#more-experiments').on('click', function () {
                var $this = $(this);
                $this.data("oldtext", $this.text());
                $this.text("Loading...");
                $this.attr("disabled", true);
                var url = $this.data("url") + "?page=" + page;
                $.get(url).success(function (response) {
                    var paginator = response.paginator;
                    if(!paginator.has_next)
                        $this.hide();
                    else
                        $this.show();
                    page = paginator.next_page_number;
                    $("#experiment-body").append(response.data)
                }).always(function () {
                    $this.text($this.data("oldtext"));
                    $this.attr("disabled", false);
                });
            });
        });
    </script>
    {% include 'genome/partials/ad_popup.html' %}

{% endblock %}